/**
 * JARSOL AUTONOMOUS AGENT POLICY ENGINE
 * Standard: "AI Proposes. Policy Verifies. Human Authorizes."
 *
 * Enforces deterministic mathematical and economic bounds on all trade intents
 * generated by autonomous agent workflows before signature creation.
 */

export interface AgentTradeProposal {
  proposalId: string;
  sourceAgent: string;
  network: 'devnet' | 'testnet' | 'mainnet-beta';
  tokenIn: string;
  tokenOut: string;
  amountInSol: number;
  maxSlippageBps: number;
  rationale: string;
  timestamp: string;
}

export interface PolicyRule {
  id: string;
  description: string;
  enforce: (proposal: AgentTradeProposal) => { passed: boolean; reason?: string };
}

export interface PolicyValidationResult {
  passed: boolean;
  proposalId: string;
  violations: string[];
  evaluatedRulesCount: number;
  humanAuthorizationRequired: true; // Invariant: AI can never bypass human wallet signature
  sanitizedIntent: AgentTradeProposal | null;
  timestamp: string;
}

export const DEFAULT_POLICY_CONFIG = {
  maxAmountInSol: 0.5,
  maxSlippageBps: 100, // 1%
  allowedTokens: ['SOL', 'JARSOL', 'USDC', 'JUP', 'RAY'],
  blockedNetworks: ['mainnet-beta'], // Mainnet autonomous trading is strictly disabled
  requireHumanSignature: true,
};

export class PolicyEngine {
  private rules: PolicyRule[] = [];

  constructor() {
    this.initializeRules();
  }

  private initializeRules() {
    // Rule 1: Trade Amount Cap
    this.rules.push({
      id: 'RULE_MAX_AMOUNT',
      description: `Trade amount cannot exceed ${DEFAULT_POLICY_CONFIG.maxAmountInSol} SOL per intent`,
      enforce: (p) => ({
        passed: p.amountInSol > 0 && p.amountInSol <= DEFAULT_POLICY_CONFIG.maxAmountInSol,
        reason: p.amountInSol > DEFAULT_POLICY_CONFIG.maxAmountInSol
          ? `Amount ${p.amountInSol} SOL exceeds max limit of ${DEFAULT_POLICY_CONFIG.maxAmountInSol} SOL`
          : p.amountInSol <= 0
          ? 'Amount must be positive'
          : undefined,
      }),
    });

    // Rule 2: Token Allowlist
    this.rules.push({
      id: 'RULE_TOKEN_ALLOWLIST',
      description: `Tokens must be in the approved allowlist: ${DEFAULT_POLICY_CONFIG.allowedTokens.join(', ')}`,
      enforce: (p) => {
        const inAllowed = DEFAULT_POLICY_CONFIG.allowedTokens.includes(p.tokenIn.toUpperCase());
        const outAllowed = DEFAULT_POLICY_CONFIG.allowedTokens.includes(p.tokenOut.toUpperCase());
        const passed = inAllowed && outAllowed;
        return {
          passed,
          reason: !passed ? `Unsupported token pair (${p.tokenIn} -> ${p.tokenOut})` : undefined,
        };
      },
    });

    // Rule 3: Slippage Guardrail
    this.rules.push({
      id: 'RULE_SLIPPAGE_LIMIT',
      description: `Max slippage cannot exceed ${DEFAULT_POLICY_CONFIG.maxSlippageBps / 100}% (${DEFAULT_POLICY_CONFIG.maxSlippageBps} bps)`,
      enforce: (p) => ({
        passed: p.maxSlippageBps > 0 && p.maxSlippageBps <= DEFAULT_POLICY_CONFIG.maxSlippageBps,
        reason: p.maxSlippageBps > DEFAULT_POLICY_CONFIG.maxSlippageBps
          ? `Slippage ${p.maxSlippageBps} bps exceeds max limit of ${DEFAULT_POLICY_CONFIG.maxSlippageBps} bps`
          : undefined,
      }),
    });

    // Rule 4: Network Isolation
    this.rules.push({
      id: 'RULE_NETWORK_ISOLATION',
      description: 'Autonomous execution on Mainnet-Beta is permanently blocked',
      enforce: (p) => ({
        passed: !DEFAULT_POLICY_CONFIG.blockedNetworks.includes(p.network),
        reason: DEFAULT_POLICY_CONFIG.blockedNetworks.includes(p.network)
          ? `Network ${p.network} is fail-closed locked for autonomous agent execution`
          : undefined,
      }),
    });
  }

  /**
   * Evaluates an agent's trade proposal against all active security policies.
   * Fail-closed: any violation causes immediate rejection.
   */
  public evaluate(proposal: AgentTradeProposal): PolicyValidationResult {
    const violations: string[] = [];

    for (const rule of this.rules) {
      const res = rule.enforce(proposal);
      if (!res.passed) {
        violations.push(`[${rule.id}] ${res.reason || rule.description}`);
      }
    }

    const passed = violations.length === 0;

    return {
      passed,
      proposalId: proposal.proposalId,
      violations,
      evaluatedRulesCount: this.rules.length,
      humanAuthorizationRequired: true,
      sanitizedIntent: passed ? proposal : null,
      timestamp: new Date().toISOString(),
    };
  }
}

export const globalPolicyEngine = new PolicyEngine();
